# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
